# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('last_use', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Buydetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('note', models.CharField(max_length=50)),
                ('buyable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qsh.Buyable')),
            ],
        ),
        migrations.CreateModel(
            name='Shoplist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='shoplist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qsh.User'),
        ),
        migrations.AddField(
            model_name='buydetail',
            name='shoplist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qsh.Shoplist'),
        ),
        migrations.AddField(
            model_name='buyable',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qsh.User'),
        ),
    ]
