# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsh', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buydetail',
            name='shoplist',
        ),
        migrations.AddField(
            model_name='shoplist',
            name='buydetails',
            field=models.ManyToManyField(to='qsh.Buydetail'),
        ),
    ]
