# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 19:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qsh', '0002_auto_20170402_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoplist',
            name='buydetails',
        ),
        migrations.AddField(
            model_name='buydetail',
            name='shoplist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='qsh.Shoplist'),
            preserve_default=False,
        ),
    ]
