# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 13:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qsh', '0005_auto_20170405_0843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyable',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='shoplist',
            old_name='user',
            new_name='owner',
        ),
    ]
